packages:
  - corpSetup/c11cloudfront/source/authGuardLambdaEdge
  - corpSetup/c11cloudfront/source/loginApp
onlyBuiltDependencies:
  - snyk25h
  - snyk25h6
  - snyk
  - snyk@1.1300.2
  - scarf
  - azure-functions-core-tools
  - esbuild
  - protobufjs
